_core:
  default_config_hash: fOKpdtzU8zyx5g4PxFgM-lh1uo_izXX_xyNeaaqwkV4
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: themes/custom/saho_shop/logo.svg
  use_default: false
saho_shop_enable_color: 1
base_primary_color: '#990000'
base_light_color: '#F0F1F5'
base_dark_color: '#990000'
body_text_color: '#333333'
body_background_color: '#FFFFFF'
inline_logo: 1
saho_shop_submit_button: 0
message_type: alerts
toast_placement: top_left
form_style: floating_labels
form_required_indicator: icon
form_field_spacing: normal
quantity_input_plus_minus: 1
success_buttons_exact: "Add to cart\r\nDownload feature\r\nSave and add\r\nAdd another item\r\nUpdate style\r\nAdd effect\r\nAdd and configure\r\nSave configuration\r\nInstall and set as default\r\nAdd the entire list to cart\r\nCreate\r\nInstall\r\nSave\r\nSend\r\nWrite\r\nContinue\r\nPay\r\n"
success_buttons_contains: "Confirm\r\nFilter\r\nSubmit\r\nSearch\r\nSettings\r\nUpload\r\nApply\r\nCheckout\r\n"
secondary_buttons: "Edit\r\n"
danger_buttons: "Delete\r\nRemove\r\nReset\r\nUninstall\r\n"
warning_buttons: "Export\r\nImport\r\nRestore\r\nRebuild\r\n"
info_buttons: ''
outline_primary_buttons: "Update\r\n"
outline_secondary_buttons: ''
outline_success_buttons: "Recalculate\r\nPreview\r\n"
outline_danger_buttons: ''
outline_warning_buttons: ''
outline_info_buttons: ''
button_icon_mappings: "Add to cart|basket\r\nAdd|add\r\nPay|card\r\nWishlist|heart\r\n"
cart_icon: basket
cart_show_label: false
cart_label: '@count items'
cart_count_circle: true
cart_dropdown_animation: 'null'
cart_dropdown_position: right
cart_hover_display: false
cart_contents_title: 'Shopping bag'
cart_contents_bg: primary
cart_contents_text: white
product_teaser: saho_shop
product_image_display: default
product_image_lightbox_theme: dark
carousel_arrows: 1
carousel_dots: 1
carousel_thumbs: 1
carousel_functionality: fancybox
focused_checkout: 1
focused_user_auth: 1
focused_user_auth_show_bg_image: 0
focused_user_auth_bg_image: {  }
focused_user_auth_bg_color: light
checkout_mobile_floating_order_summary: 1
checkout_completion_minimal: 1
checkout_pane_variant: title-outside
checkout_pane_collapsible: 0
checkout_pane_show_icons: 0
focused_paths: ''
focused_page_logo: 1
focused_page_use_default_theme_logo: 0
focused_page_show_back_button: 1
focused_page_back_button_text: ''
focused_page_show_cart_button: 1
focused_page_cart_button_text: ''
focused_page_show_icons: 1
focused_checkout_form_step_title: 0
focused_checkout_copyright: 1
focused_checkout_show_progress: 0
focused_page_header_container: container-lg
focused_page_header_container_custom: ''
focused_page_container: container-lg
focused_page_container_custom: ''
focused_checkout_main_column: col-xl-6
focused_page_override_colors: 0
focused_page_bg_color: '#000000'
focused_page_text_color: '#000000'
focused_page_sidebar_bg_color: '#000000'
focused_page_sidebar_text_color: '#000000'
focused_page_override_header_colors: 0
focused_page_header_bg_color: '#000000'
focused_page_header_text_color: '#000000'
focused_page_header_border_color: '#000000'
main_container: container-xl
main_container_class: ''
navigation_toggle_visibility: 0
navigation_toggle_text: Menu
navigation_position: start
navigation_logo: 1
navigation_body_scrolling: 0
navigation_backdrop: 0
region_class_navigation: 'bg-primary opacify-links text-white'
region_class_top_bar: 'position-relative bg-dark py-2 opacify-links text-white'
region_container_top_bar: container-xl
region_class_header: 'py-5 mt-lg-4'
region_container_header: container-xl
region_class_highlighted: ''
region_container_highlighted: container-xl
region_class_help: ''
region_container_help: ''
region_class_sidebar_first: 'col-lg-3 me-lg-4 order-first'
region_container_sidebar_first: ''
region_class_content: col
region_container_content: ''
region_class_sidebar_second: col-lg-3
region_container_sidebar_second: ''
region_class_footer: 'bg-dark py-5 opacify-links text-white'
region_container_footer: container-xl
saho_shop_icons: 1
font_set: raleway
local_tasks_fixed: 1
address_dialog: 1
payment_method_dialog: 1
saho_shop_color_scheme: default
