_core:
  default_config_hash: T8JnF2uRNsCWpi2Tc-Jlw0EksMSZekKjeD7lYR6mS_k
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: ''
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
  node_user_picture: false
logo:
  path: ''
  url: ''
  use_default: false
copyright_text: 'Copyright © @year · All rights reserved South African History Online (SAHO)'
fixed_header: 1
schemas:
  bootstrap: 8000
  sshop: 8000
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
  footer_first: ''
  footer_second: ''
  footer_third: ''
  footer_fourth: ''
table_responsive: '-1'
table: ''
fluid_container: 1
modal_enabled: 0
popover_enabled: 0
tooltip_enabled: 0
cdn_provider: ''
navbar_position: fixed-top
display_theme_credits: 0
cdn_theme: ''
cdn_cache_ttl_versions: 0
cdn_cache_ttl_themes: 0
cdn_cache_ttl_assets: 0
cdn_cache_ttl_library: 0
reset: 'Reset Broken Cache'
apply: Apply
reset_http_request_cache: ''
breadcrumb_home: 1
