blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Ways to Contribute (Non-Technical)
    url: https://github.com/South-African-History-Online/sahistory-web/issues/new?template=contribution_guide.yml
    about: Discover exciting ways to contribute to South African History Online beyond coding!
  
  - name: ğŸ“š General Enquiries or Editorial Support
    url: https://www.sahistory.org.za/contact
    about: Please use this for general site-related questions or non-technical feedback.