# Schema for the theme setting configuration file of the SahoShop theme.

saho_shop.settings:
  type: theme_settings
  label: 'SahoShop settings'
  mapping:
    # General settings
    saho_shop_enable_color:
      type: integer
      label: 'Enable Color Scheme'
    base_primary_color:
      type: string
      label: 'Primary base color'
    base_light_color:
      type: string
      label: 'Light base color'
    base_dark_color:
      type: string
      label: 'Dark base color'
    body_text_color:
      type: string
      label: 'Body text color'
    body_background_color:
      type: string
      label: 'Body background color'
    inline_logo:
      type: integer
      label: 'Inline SVG logo'
    saho_shop_submit_button:
      type: integer
      label: 'Convert input submit to button element'
    fieldset_accordion:
      type: integer
      label: 'Fieldset accordion'

    # Message settings
    message_type:
      type: string
      label: 'Messages type'
    toast_placement:
      type: string
      label: 'Toast placement'

    # Form settings
    form_style:
      type: string
      label: 'Form style'
    form_required_indicator:
      type: string
      label: 'Required field indicator'
    form_field_spacing:
      type: string
      label: 'Field spacing'
    quantity_input_plus_minus:
      type: integer
      label: 'Enable Plus/Minus Buttons for Quantity Inputs'

    # Button styling settings
    success_buttons_exact:
      type: text
      label: 'Success Button Text (Exact Match)'
    success_buttons_contains:
      type: text
      label: 'Success Button Text (Contains)'
    secondary_buttons:
      type: text
      label: 'Secondary Button Text'
    danger_buttons:
      type: text
      label: 'Danger Button Text'
    warning_buttons:
      type: text
      label: 'Warning Button Text'
    info_buttons:
      type: text
      label: 'Info Button Text'
    outline_primary_buttons:
      type: text
      label: 'Outline Primary Button Text'
    outline_secondary_buttons:
      type: text
      label: 'Outline Secondary Button Text'
    outline_success_buttons:
      type: text
      label: 'Outline Success Button Text'
    outline_danger_buttons:
      type: text
      label: 'Outline Danger Button Text'
    outline_warning_buttons:
      type: text
      label: 'Outline Warning Button Text'
    outline_info_buttons:
      type: text
      label: 'Outline Info Button Text'
    button_icon_mappings:
      type: text
      label: 'Button Icon Mappings'

    # Cart settings
    cart_icon:
      type: string
      label: 'Cart icon'
    cart_show_label:
      type: boolean
      label: 'Show item label'
    cart_label:
      type: string
      label: 'Item label'
      translatable: true
    cart_count_circle:
      type: boolean
      label: 'Display count in circle badge'
    cart_dropdown_animation:
      type: string
      label: 'Cart dropdown animation'
    cart_dropdown_position:
      type: string
      label: 'Dropdown position'
    cart_hover_display:
      type: boolean
      label: 'Display cart contents on hover'
    cart_contents_title:
      type: string
      label: 'Cart contents title'
      translatable: true
    cart_contents_bg:
      type: string
      label: 'Cart contents background color'
    cart_contents_text:
      type: string
      label: 'Cart contents text color'

    # Commerce settings
    product_teaser:
      type: string
      label: 'Product teaser'
    product_image_display:
      type: string
      label: 'Product image display'
    product_image_lightbox_theme:
      type: string
      label: 'Lightbox theme'
    carousel_arrows:
      type: integer
      label: 'Show navigation arrows'
    carousel_dots:
      type: integer
      label: 'Show navigation dots'
    carousel_thumbs:
      type: integer
      label: 'Show thumbnail navigation'
    carousel_functionality:
      type: string
      label: 'Carousel functionality'

    # Checkout settings
    focused_checkout:
      type: integer
      label: 'Enable Focused Checkout'
    focused_user_auth:
      type: integer
      label: 'Enable Focused User Authentication Pages'
    focused_user_auth_show_bg_image:
      type: integer
      label: 'Show Background Image'
    focused_user_auth_bg_image:
      type: sequence
      label: 'Focused User Auth Background Image'
    focused_user_auth_bg_color:
      type: string
      label: 'Focused User Auth Background Color'
    checkout_mobile_floating_order_summary:
      type: integer
      label: 'Mobile Floating Order Summary'
    checkout_completion_minimal:
      type: integer
      label: 'Minimal Checkout Completion'

    # Checkout pane settings
    checkout_pane_variant:
      type: string
      label: 'Checkout Pane Variant'
    checkout_pane_collapsible:
      type: integer
      label: 'Make Checkout Panes Collapsible'
    checkout_pane_show_icons:
      type: integer
      label: 'Show Icons in Checkout Panes'

    # Focused checkout paths
    focused_paths:
      type: text
      label: 'Additional Focused Paths'

    # Focused checkout header settings
    focused_page_logo:
      type: integer
      label: 'Show Logo'
    focused_page_use_default_theme_logo:
      type: integer
      label: 'Use default site logo on focused pages'
    focused_page_show_back_button:
      type: integer
      label: 'Show Back Button'
    focused_page_back_button_text:
      type: string
      label: 'Back Button Text'
      translatable: true
    focused_page_show_cart_button:
      type: integer
      label: 'Show Cart Button'
    focused_page_cart_button_text:
      type: string
      label: 'Cart Button Text'
      translatable: true
    focused_page_show_icons:
      type: integer
      label: 'Show Icons in Header'

    # Focused checkout content settings
    focused_checkout_form_step_title:
      type: integer
      label: 'Show Form Step Title'
    focused_checkout_copyright:
      type: integer
      label: 'Show Copyright'
    focused_checkout_show_progress:
      type: integer
      label: 'Show Checkout Progress'

    # Focused checkout layout settings
    focused_page_header_container:
      type: string
      label: 'Header Container Width'
    focused_page_header_container_custom:
      type: string
      label: 'Custom Header Container Width'
    focused_page_container:
      type: string
      label: 'Content Container Width'
    focused_page_container_custom:
      type: string
      label: 'Custom Content Container Width'
    focused_checkout_main_column:
      type: string
      label: 'Main column width'

    # Focused checkout color settings
    focused_page_override_colors:
      type: integer
      label: 'Override Default Body Colors'
    focused_page_bg_color:
      type: string
      label: 'Background Color'
    focused_page_text_color:
      type: string
      label: 'Text Color'
    focused_page_sidebar_bg_color:
      type: string
      label: 'Order Summary Background Color'
    focused_page_sidebar_text_color:
      type: string
      label: 'Order Summary Text Color'
    focused_page_override_header_colors:
      type: integer
      label: 'Override Default Header Colors'
    focused_page_header_bg_color:
      type: string
      label: 'Header Background Color'
    focused_page_header_text_color:
      type: string
      label: 'Header Text Color'
    focused_page_header_border_color:
      type: string
      label: 'Header Border Color'

    # Region settings
    main_container:
      type: string
      label: 'Main container size'
    main_container_class:
      type: string
      label: 'Main content classes'

    # Navigation settings
    navigation_toggle_visibility:
      type: integer
      label: 'Disable navigation toggle on Desktop'
    navigation_toggle_text:
      type: string
      label: 'Navigation toggle text'
      translatable: true
    navigation_position:
      type: string
      label: 'Navigation placement'
    navigation_logo:
      type: integer
      label: 'Display Logo'
    navigation_body_scrolling:
      type: integer
      label: 'Body Scrolling'
    navigation_backdrop:
      type: integer
      label: 'Body Backdrop'
    region_class_navigation:
      type: string
      label: 'Navigation region classes'

    # Dynamic region settings (these will be generated for each region)
    region_class_top_bar:
      type: string
      label: 'Top Bar region classes'
    region_container_top_bar:
      type: string
      label: 'Top Bar container type'
    region_class_header:
      type: string
      label: 'Header region classes'
    region_container_header:
      type: string
      label: 'Header container type'
    region_class_highlighted:
      type: string
      label: 'Highlighted region classes'
    region_container_highlighted:
      type: string
      label: 'Highlighted container type'
    region_class_help:
      type: string
      label: 'Help region classes'
    region_container_help:
      type: string
      label: 'Help container type'
    region_class_sidebar_first:
      type: string
      label: 'Sidebar First region classes'
    region_container_sidebar_first:
      type: string
      label: 'Sidebar First container type'
    region_class_content:
      type: string
      label: 'Content region classes'
    region_container_content:
      type: string
      label: 'Content container type'
    region_class_sidebar_second:
      type: string
      label: 'Sidebar Second region classes'
    region_container_sidebar_second:
      type: string
      label: 'Sidebar Second container type'
    region_class_footer:
      type: string
      label: 'Footer region classes'
    region_container_footer:
      type: string
      label: 'Footer container type'

    # Font and icon settings
    saho_shop_icons:
      type: integer
      label: 'Use icons'
    font_set:
      type: string
      label: 'Font libraries'

    # Layout Builder settings
    local_tasks_fixed:
      type: integer
      label: 'Fixed local tasks'

    # Address settings
    address_dialog:
      type: integer
      label: 'Display address operations in dialog'

    # Payment method settings
    payment_method_dialog:
      type: integer
      label: 'Display payment method operations in dialog'
