saho_statistics.settings:
  type: config_object
  label: 'SAHO Statistics settings'
  mapping:
    track_searches:
      type: boolean
      label: 'Enable search query tracking'
    search_query_retention:
      type: integer
      label: 'Data retention period (days)'
